### ISSUE TITLE
Presentaciones

### ISSUE THREAD

**Issue by UlisesGascon** [Fictizia/Curso-JS-Avanzado-para-desarrolladores-Front-end_ed1#1]
Hola!

Usemos este espacio para conocernos un poco más... :-)

Recordad que estos [_issues_](https://github.com/Fictizia/Curso-JS-Avanzado-para-desarrolladores-Front-end_ed1/issues) nos permiten abrir y participar en debates, compartir recursos, plantear preguntas y muchas cosas más! 

Podemos usar [Markdown](https://guides.github.com/features/mastering-markdown/) para salirnos del texto plano y enriquecer nuestras aportaciones.

**Comment by Alvaro07** [comment]
Hola,

Soy Alvaro, desarrollador front desde hace 6/7 años, me decidí por este curso ya que creo que es el momento de dar un salto de calidad en el mundo javascript, pudiendo aplicarlo tanto en mi entorno laboral como en mis proyectos como freelance, seguro que aprendemos muchismo.

un placer, 
y un saludo a todos!!

**Comment by barleby** [comment]
Hola, Soy **José**. Siempre he aprendido javascript por mi cuenta y leyendo, así que seguramente tengo malos hábitos/prácticas que nunca nadie me ha corregido. Trabajo como desarrollador de FE desde hace 11 años. El hecho de que en mi equipo hayamos sido siempre yo y, a veces, otra persona, ha hecho que siempre estuviéramos hasta arriba de trabajo como para investigar nuevos frameworks y formas de implementar el FE. 
Creo que es el momento óptimo para hacer este curso (y presencial aún mejor) para "modernizar" mis conocimientos y poder quitarme carga de trabajo con las nuevas herramientas que hay.
Saludos!
