### ISSUE TITLE
Ejemplos de firebase.googleblog.com

### ISSUE THREAD

**Issue by barleby** [Fictizia/Curso-JS-Avanzado-para-desarrolladores-Front-end_ed1#7]
@UlisesGascon estoy consultando los artículos de queries de Firebase que nos dejaste al principio y no sé si hago algo mal o Google ha quitado ciertas referencias ya.

En la URL: https://firebase.googleblog.com/2013/10/queries-part-1-common-sql-queries.html
dan el siguiente enlace:
_We're going to work with the [examples-sql-queries](https://examples-sql-queries.firebaseio.com/) Firebase for all the examples. Feel free to browse the data and get a feel for the structure._ 

pero al hacer click en el enlace de ejemplo no me lleva a la BBDD (lo que me interesaba era verla para ver su estructura). Me redirige siempre a: https://console.firebase.google.com/

Otras que salían en los ejemplos (las de dinosaurios) me pasa lo mismo. Me redirige a https://console.firebase.google.com/

**Comment by UlisesGascon** [comment]
Hola @barleby!

Perdón por el retraso en contestar...

Los ejemplos de la documentación antigua ya han desaparecido, con la migración definitiva de la versión 3.x

He podido salvar algunos:
- **dinosaur-facts** -> https://dinosaur-facts-b1e42.firebaseio.com permisos de lectura completos
- **docs-examples** -> https://docs-examples-4acaf.firebaseio.com permisos de lectura completos

Pero por desgracia de los artículos de queries SQL, no.

De todas formas, la documentación antigua aunque ya no esta online puede ser consultada desde el web.archive. 

[Documentación previa](http://web.archive.org/web/20170110005455/https://www.firebase.com/docs/)
